prework/urls.py
from django.urls import path, register_converter

from classes import converters
from . import views

register_converter(converters.SubjectConverter, 'subj')

app_name = 'prework'
urlpatterns = [
    path('', views.index, name='index'),
    path('<subj:subject>/', views.list_videos, name='list_videos'),
    path('video/<subj:subject>/<slug:slug>/', views.show_video, name='show_video'),
]

preworkhub/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('prework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

videos/urls.py
from django.urls import path, register_converter

from classes import converters
from . import views

register_converter(converters.SubjectConverter, 'subj')

app_name = 'videos'
urlpatterns = [
    path('', views.index, name='index'),
    path('<subj:subject>/', views.list_videos, name='list_videos'),
    path('video/<subj:subject>/<slug:slug>/', views.show_video, name='show_video'),
]

preworkhub/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} - Prework Hub</title>
    <link rel="stylesheet" href="{% static 'mini.min.css' %}">
    <link rel="stylesheet" href="{% static 'base.css' %}">
</head>
<body>
<header class="sticky">
    <a href="{% url 'prework:index' %}" class="logo">Prework</a>
    <a href="{% url 'prework:list_videos' 'calc' %}" class="button">Calculus</a>
    <a href="{% url 'prework:list_videos' 'stats' %}" class="button">Statistics</a>
</header>
<div class="container">
    {% block content %}{% endblock %}
</div>
</body>
</html>