preworkhub/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('prework.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

videos/urls.py
from django.urls import path, register_converter

from classes import converters
from . import views

register_converter(converters.SubjectConverter, 'subj')

app_name = 'videos'
urlpatterns = [
    path('', views.index, name='index'),
    path('<subj:subject>/', views.list_videos, name='list_videos'),
    path('video/<subj:subject>/<slug:slug>/', views.show_video, name='show_video'),
]

videos/models.py
import re
from datetime import date
from django.db import models


class PreworkVideo(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateField('Date created', default=date.today)
    # subject = models.CharField(db_index=True, max_length=5, choices=CLASS_CHOICES)
    subject = models.ForeignKey('classes.Subject', db_index=False, on_delete=models.PROTECT)
    unit = models.ForeignKey('classes.Unit', on_delete=models.PROTECT)
    video_link = models.CharField(max_length=100)

    # These are SmallIntegerFields because we aren't going to be having class numbers above 32767
    # class_num = models.SmallIntegerField()
    class_date = models.ForeignKey('classes.ClassDate', on_delete=models.PROTECT)
    video_num = models.SmallIntegerField(default=1)

    slug = models.SlugField('URL', unique=True)

    notes = models.TextField(blank=True)

    def __str__(self):
        return self.title

    @property
    def video_id(self):
        pattern = re.compile('(0[A-Za-z0-1])\w+')
        match = pattern.search(self.video_link)
        if match:
            return match.group()
        else:
            return ''

    @property
    def embed_link(self):
        return f"https://drive.google.com/file/d/{self.video_id}/preview"

    @property
    def full_video_id(self):
        return f"{self.class_date.day}-{self.video_num}"
    full_video_id.fget.short_description = 'Class and Video Number'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('videos:show_video', args=[self.subject, self.slug])

    # TODO: create previous and next methods that use the video num and day

    class Meta:
        ordering = ['-created']
        get_latest_by = 'created'


class VideoMetadata(models.Model):
    student = models.ForeignKey('classes.Student', on_delete=models.CASCADE)
    video = models.ForeignKey(PreworkVideo, on_delete=models.CASCADE)
    got_it = models.BooleanField(default=False)
    watched = models.BooleanField(default=False)

videos/views.py
from django.shortcuts import get_object_or_404, render

from .models import PreworkVideo
from classes.models import Subject


def index(request):
    stats_subj = Subject.objects.get(name='stats')
    calc_subj = Subject.objects.get(name='calc')
    stats = PreworkVideo.objects.select_related('subject', 'class_date').filter(subject=stats_subj)[:10]
    calc = PreworkVideo.objects.select_related('subject', 'class_date').filter(subject=calc_subj)[:10]
    return render(request, 'videos/index.html', {'stats': stats, 'calc': calc})


def list_videos(request, subject):
    subj = Subject.objects.get(name=subject)
    videos = PreworkVideo.objects.select_related('subject', 'class_date').filter(subject=subj)
    return render(request, 'videos/list_videos.html', {'videos': videos, 'subject': subj})


def show_video(request, subject, slug):
    video = get_object_or_404(PreworkVideo, slug=slug)
    return render(request, 'videos/show_video.html', {'video': video})

videos/templates/videos/index.html
{% extends 'base.html' %}

{% block title %}Prework Videos{% endblock %}

{% block content %}
    <div class="row">
        <h1>Prework Videos</h1>
    </div>
    <div class="row">
        <div class="card">
            <div class="section">
                <h2>Calculus<small>{{ calc.count }} video{{ calc.count|pluralize }}</small></h2>
                <p>10 most recent Calculus video{{ calc.count|pluralize }}</p>
            </div>
            <div class="section">
                <ul>
                    {% for video in calc %}
                        <li><a href="{% url 'videos:show_video' video.subject.name video.slug %}">{{ video.title }}</a> Class {{ video.class_date.day }} video {{ video.video_num }}</li>
                    {% endfor %}
                </ul>
                <p><a href="{% url 'videos:list_videos' 'calc' %}">View All</a></p>
            </div>
        </div>
        <div class="card">
            <div class="section">
                <h2>Statistics<small>{{ stats.count }} video{{ stats.count|pluralize }}</small></h2>
                <p>10 most recent Statistics video{{ stats.count|pluralize }}</p>
            </div>
            <div class="section">
                <ul>
                    {% for video in stats %}
                        <li><a href="{% url 'videos:show_video' video.subject.name video.slug %}">{{ video.title }}</a> Class {{ video.class_date.day }} video {{ video.video_num }}</li>
                    {% endfor %}
                </ul>
                <p><a href="{% url 'videos:list_videos' 'stats' %}">View All</a></p>
            </div>
        </div>
    </div>
{% endblock %}

videos/templates/videos/list_videos.html
{% extends 'base.html' %}

{% block title %}Prework Videos for {{ subject }}{% endblock %}

{% block content %}
    <h1>{{ subject }}</h1>
    <ul>
        {% for video in videos %}
            <li><a href="{% url 'videos:show_video' video.subject.name video.slug %}">{{ video.title }}</a>
                Class {{ video.class_date.day }} video {{ video.video_num }}</li>
        {% endfor %}
    </ul>
{% endblock %}